name: Documentation

on:
  push:
    branches:
      - master

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install doxygen
        run: apt install doxygen

      - name: Generate documentation
        run: doxygen doxygen-config

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: html
